apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-apps
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: nginx
        image: 599476212737.dkr.ecr.ap-southeast-2.amazonaws.com/ga-repo:4d36080f24c024ea7b8454103fadb5533c97e4d5
